[workspace]
resolver = "3"
members = [
    "ferros_kernel",
    "ferros_hal",
    "ferros_vault",
    "ferros_ledger",
    "tools/mkimg",
    "tools/ferros-bridge",
]

[workspace.package]
edition = "2024"
license = "MIT"

[profile.release]
opt-level = "s"       # size-optimized for embedded
lto = true
codegen-units = 1
panic = "abort"
