[workspace]
resolver = "3"
members = [
    "ferros_layout",
    "ferros_kernel",
    "ferros_hal",
    "ferros_hal_m1",
    "vault",
    "ferros_ledger",
    "ferros_pt",
    "ferros_seed",
    "tools/mkimg",
    "tools/ferros-bridge",
    "tools/install",
    "payloads/hello",
    "payloads/usbprobe",
]

[workspace.package]
edition = "2024"
license = "Apache-2.0"

[profile.release]
opt-level = "s"       # size-optimized for embedded
lto = true
codegen-units = 1
panic = "abort"
